import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import '../../../core/theme.dart';
import '../../../data/services/supabase_service.dart';

/// REAL invoices — auto-generated by the backend (base + 18% GST) the moment
/// a shipment is marked completed. No sample data.
class InvoicesScreen extends StatefulWidget {
  const InvoicesScreen({super.key});

  @override
  State<InvoicesScreen> createState() => _InvoicesScreenState();
}

class _InvoicesScreenState extends State<InvoicesScreen> {
  List<Map<String, dynamic>>? _invoices;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    try {
      final v = await SupabaseService.getInvoices();
      if (mounted) setState(() => _invoices = v);
    } catch (_) {
      if (mounted) setState(() => _invoices ??= []);
    }
  }

  @override
  Widget build(BuildContext context) {
    final currency =
        NumberFormat.currency(locale: 'en_IN', symbol: '₹', decimalDigits: 0);
    final invoices = _invoices ?? [];

    return Scaffold(
      backgroundColor: AppColors.canvas,
      appBar: AppBar(title: const Text('Tax Invoices & GST')),
      body: RefreshIndicator(
        onRefresh: _load,
        child: _invoices != null && invoices.isEmpty
            ? ListView(children: [
                const SizedBox(height: 120),
                const Icon(Icons.receipt_long_outlined,
                    size: 48, color: AppColors.inkMuted),
                const SizedBox(height: 12),
                Center(
                    child: Text('No invoices yet.',
                        style:
                            GoogleFonts.inter(fontWeight: FontWeight.w700))),
                Center(
                    child: Text(
                        'Invoices generate automatically when a shipment completes.',
                        style: GoogleFonts.inter(
                            fontSize: 12, color: AppColors.inkMuted))),
              ])
            : ListView.separated(
                padding: const EdgeInsets.all(16),
                itemCount: invoices.length,
                separatorBuilder: (_, __) => const SizedBox(height: 12),
                itemBuilder: (context, index) {
                  final inv = invoices[index];
                  final paid = inv['status'] == 'paid';
                  String date = '';
                  final d =
                      DateTime.tryParse('${inv['created_at'] ?? ''}')?.toLocal();
                  if (d != null) date = DateFormat('d MMM yyyy').format(d);
                  return Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text('${inv['invoice_no']}',
                                  style: GoogleFonts.inter(
                                      fontWeight: FontWeight.w800,
                                      fontSize: 14)),
                              Container(
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 8, vertical: 4),
                                decoration: BoxDecoration(
                                    color: paid
                                        ? const Color(0xFFECFDF5)
                                        : const Color(0xFFFEF3C7),
                                    borderRadius: BorderRadius.circular(6)),
                                child: Text(paid ? 'PAID' : 'TO BE PAID',
                                    style: GoogleFonts.inter(
                                        fontSize: 10,
                                        fontWeight: FontWeight.w800,
                                        color: paid
                                            ? AppColors.success
                                            : AppColors.warning)),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Text('${inv['route'] ?? ''}',
                              style: GoogleFonts.inter(
                                  fontWeight: FontWeight.w700, fontSize: 15)),
                          Text('Billed on $date',
                              style: GoogleFonts.inter(
                                  fontSize: 12, color: AppColors.inkMuted)),
                          const SizedBox(height: 12),
                          const Divider(height: 1, color: AppColors.border),
                          const SizedBox(height: 10),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(
                                  'Base: ${currency.format((inv['base_inr'] as num?) ?? 0)} + GST ${currency.format((inv['gst_inr'] as num?) ?? 0)}',
                                  style: GoogleFonts.inter(
                                      fontSize: 12,
                                      color: AppColors.inkMuted)),
                              Text(
                                  currency.format(
                                      (inv['total_inr'] as num?) ?? 0),
                                  style: GoogleFonts.inter(
                                      fontWeight: FontWeight.w900,
                                      fontSize: 16,
                                      color: AppColors.slateDark)),
                            ],
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
      ),
    );
  }
}
